package registry

import "errors"

var (
	ErrInvalidModuleName           = errors.New("invalid module name")
	ErrInvalidVersion              = errors.New("invalid version")
	ErrModuleNotFound              = errors.New("module not found")
	ErrModuleGitLabProjectNotFound = errors.New("module gitlab project mapping not found")
	ErrModuleAlreadyExists         = errors.New("module already exists")
	ErrModuleVersionAlreadyExists  = errors.New("module version already exists")
	ErrInvalidGitLabBaseURL        = errors.New("invalid gitlab base url")
	ErrInvalidGitLabProjectID      = errors.New("invalid gitlab project id")
	ErrInvalidGitLabProjectPath    = errors.New("invalid gitlab project path")
	ErrGitLabProjectAlreadyLinked  = errors.New("gitlab project already linked to another module")
	ErrArtifactTooLarge            = errors.New("artifact too large")
	ErrInvalidOrExpiredToken       = errors.New("invalid or expired token")
	ErrStorageFailure              = errors.New("storage failure")
	ErrArtifactRequired            = errors.New("artifact required")
	ErrBufConfigNotFound           = errors.New("buf config not found")
	ErrBufBuildFailed              = errors.New("buf build failed")
	ErrBufLintFailed               = errors.New("buf lint failed")
	ErrBufBreakingFailed           = errors.New("buf breaking failed")
	ErrDescriptorExtractionFailed  = errors.New("descriptor extraction failed")
	ErrUnsafeArchive               = errors.New("unsafe archive")
	ErrBufWorkflowUnavailable      = errors.New("buf workflow unavailable")
	ErrBufBreakingUnavailable      = errors.New("buf breaking unavailable")
	ErrInvalidAgainst              = errors.New("invalid against value")
	ErrBaselineVersionNotFound     = errors.New("baseline version not found")
	ErrBaselineBufImageMissing     = errors.New("baseline buf image missing")
	ErrInvalidTargetRef            = errors.New("invalid target ref")
	ErrBreakingReportNotFound      = errors.New("breaking report not found")
)
